const imagensDisponiveis = {
  // Goleiros Atuais
  "Hugo Souza": "hugo-souza.png",
  "Felipe Longo": "felipe-longo.png",
  Kauê: "kaue.png",
  "Matheus Donelli": "matheus-donelli.png",

  // Laterais
  Matheuzinho: "matheuzinho.png",
  "Matheus Bidu": "matheus-bidu.png",
  Hugo: "hugo-lateral.png",
  "Fabrizio Angileri": "fabrizio-angileri.png",
  "Pedro Milans": "pedro-milans.png",
  "Hugo Farias": "hugo-farias.png",
  Fagner: "fagner.png",

  // Zagueiros
  "André Ramalho": "andre-ramalho.png",
  "Gustavo Henrique": "gustavo-henrique.png",
  "Félix Torres": "felix-torres.png",
  "João Pedro": "joao-pedro.png",
  "Gabriel Paulista": "gabriel-paulista.png",
  Cacá: "caca.png",

  // Volantes
  Raniele: "raniele.png",
  Charles: "charles.png",
  "Breno Bidon": "breno-bidon.png",
  Maycon: "maycon.png",
  "Alex Santana": "alex-santana.png",
  "José Martínez": "jose-martinez.png",
  Allan: "allan.png",
  "Matheus Pereira": "matheus-pereira.png",
  André: "andre.png",
  Ryan: "ryan.png",

  // Meias
  "André Carrillo": "andre-carrillo.png",
  "Rodrigo Garro": "rodrigo-garro.png",
  Bahia: "bahia.png",
  Dieguinho: "dieguinho.png",
  "Zakaria Labyad": "zakaria-labyad.png",
  "Jesse Lingard": "jesse-lingard.png",

  // Atacantes
  "Yuri Alberto": "yuri-alberto.png",
  "Memphis Depay": "memphis-depay.png",
  Vitinho: "vitinho.jpg",
  Kayke: "kayke.png",
  "Gui Negão": "gui-negao.png",
  "Pedro Raul": "pedro-raul.png",
  "Kaio César": "kaio-cesar.png",
  "Ângel Romero": "angel-romero.png",
  "Héctor Hernández": "hector-hernandez.png",
  "Talles Magno": "talles-magno.png",

  // Ídolos Históricos
  Cássio: "cassio.png",
  "Paolo Guerrero": "paolo-guerrero.webp",
  Ronny: "ronny.png",
  Sheik: "sheik.png",
  "Marcelinho Carioca": "marcelinho.png",
  Jô: "jo.png",
  Cantillo: "cantillo.png",
  "Du Queiroz": "du-queiroz.png",
  Giuliano: "giuliano.png",
  Rivellino: "rivellino.jpg",
  Sócrates: "socrates.png",
  Neto: "neto.png",
  Wladimir: "wladimir.png",
  Basílio: "basilio.png",
  Luizinho: "luizinho.jpg",
  Gylmar: "gylmar.jpg",
  Cláudio: "claudio.jpg",
  Vampeta: "vampeta.png",
  Dida: "dida.jpg",
  Casagrande: "casagrande.jpg",
  "Ronaldo Fenômeno": "ronaldo-fenomeno.png",
  Ricardinho: "ricardinho.jpg",
  Danilo: "danilo.png",
  "Carlos Tevez": "tevez.jpg",
  "A Pistache": "pistache.jpg",
  "Vagner Love": "vagner-love.png",
  "Luan": "luan.jpg",
  "Gil": "gil.png",
  "Fabio Santos": "fabio-santos.png",
  "Willian": "willian.png",
  "Malcom": "malcom.png",
  "Marquinhos": "marquinhos.png",
  "Murillo": "murillo.png",
  "Wesley": "wesley.png",
  "Matias Rojas": "matias-rojas.png",
  "Renato Augusto": "renato-augusto.png",
  "Roger Guedes": "roger-guedes.png",
  "Douglas": "douglas.png",
  "Adson": "adson.png",
  "Rincon": "rincon.jpeg",
  "Edilson": "edilson.png",
  "Romarinho": "romarinho.png",
  "Jadson": "jadson.png",
  "Rodriguinho": "rodriguinho.jpg",
  "Dentinho": "dentinho.webp",
};

export const jogadores = [
  // ===== GOLEIROS ATUAIS 2026 =====
  {
    nome: "Hugo Souza",
    posicao: "Goleiro",
    altura: 199,
    nascimento: "1998-07-20",
    ano_chegada: 2022,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Hugo Souza"],
    ativo: true,
  },
  {
    nome: "Felipe Longo",
    posicao: "Goleiro",
    altura: 188,
    nascimento: "2004-03-04",
    ano_chegada: 2023,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Felipe Longo"],
    ativo: true,
  },
  {
    nome: "Kauê",
    posicao: "Goleiro",
    altura: 192,
    nascimento: "2004-06-28",
    ano_chegada: 2022,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Kauê"],
    ativo: true,
  },
  {
    nome: "Matheus Donelli",
    posicao: "Goleiro",
    altura: 187,
    nascimento: "2002-03-03",
    ano_chegada: 2020,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Matheus Donelli"],
    ativo: true,
  },

  // ===== LATERAIS 2026 =====
  {
    nome: "Matheuzinho",
    posicao: "Lateral",
    altura: 176,
    nascimento: "2000-03-12",
    ano_chegada: 2024,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Matheuzinho"],
    ativo: true,
  },
  {
    nome: "Matheus Bidu",
    posicao: "Lateral",
    altura: 172,
    nascimento: "1999-02-18",
    ano_chegada: 2022,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Matheus Bidu"],
    ativo: true,
  },
  {
    nome: "Hugo",
    posicao: "Lateral",
    altura: 179,
    nascimento: "1998-03-14",
    ano_chegada: 2024,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Hugo"],
    ativo: true,
  },
  {
    nome: "Fabrizio Angileri",
    posicao: "Lateral",
    altura: 185,
    nascimento: "1994-01-15",
    ano_chegada: 2025,
    nacionalidade: "Argentino",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Fabrizio Angileri"],
    ativo: true,
  },
  {
    nome: "Pedro Milans",
    posicao: "Lateral",
    altura: 176,
    nascimento: "2002-09-11",
    ano_chegada: 2026,
    nacionalidade: "Uruguaio",
    titulos: [
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Pedro Milans"],
    ativo: true,
  },

  // ===== ZAGUEIROS 2026 =====
  {
    nome: "André Ramalho",
    posicao: "Zagueiro",
    altura: 182,
    nascimento: "1992-07-13",
    ano_chegada: 2024,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["André Ramalho"],
    ativo: true,
  },
  {
    nome: "Gustavo Henrique",
    posicao: "Zagueiro",
    altura: 196,
    nascimento: "1993-06-21",
    ano_chegada: 2022,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Gustavo Henrique"],
    ativo: true,
  },
  {
    nome: "Félix Torres",
    posicao: "Zagueiro",
    altura: 187,
    nascimento: "1997-03-11",
    ano_chegada: 2023,
    nacionalidade: "Equatoriano",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Félix Torres"],
    ativo: true,
  },
  {
    nome: "João Pedro",
    posicao: "Zagueiro",
    altura: 192,
    nascimento: "2004-01-26",
    ano_chegada: 2023,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
    ],
    imagem: imagensDisponiveis["João Pedro"],
    ativo: true,
  },
  {
    nome: "Gabriel Paulista",
    posicao: "Zagueiro",
    altura: 182,
    nascimento: "1991-03-12",
    ano_chegada: 2025,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Gabriel Paulista"],
    ativo: true,
  },
  {
    nome: "Cacá",
    posicao: "Zagueiro",
    altura: 187,
    nascimento: "1999-06-25",
    ano_chegada: 2023,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025"
    ],
    imagem: imagensDisponiveis["Cacá"],
    ativo: true,
  },

  // ===== VOLANTES 2026 =====
  {
    nome: "Raniele",
    posicao: "Volante",
    altura: 184,
    nascimento: "1998-06-18",
    ano_chegada: 2024,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Raniele"],
    ativo: true,
  },
  {
    nome: "Charles",
    posicao: "Volante",
    altura: 187,
    nascimento: "1996-07-18",
    ano_chegada: 2024,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Charles"],
    ativo: true,
  },
  {
    nome: "Breno Bidon",
    posicao: "Volante",
    altura: 178,
    nascimento: "2005-03-30",
    ano_chegada: 2024,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Breno Bidon"],
    ativo: true,
  },
  {
    nome: "Maycon",
    posicao: "Volante",
    altura: 175,
    nascimento: "1997-06-24",
    ano_chegada: 2017,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2018",
      "Campeonato Paulista 2019",
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Campeonato Brasileiro 2017",
    ],
    imagem: imagensDisponiveis["Maycon"],
    ativo: true,
  },
  {
    nome: "Alex Santana",
    posicao: "Volante",
    altura: 182,
    nascimento: "1996-02-27",
    ano_chegada: 2024,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
    ],
    imagem: imagensDisponiveis["Alex Santana"],
    ativo: true,
  },
  {
    nome: "José Martínez",
    posicao: "Volante",
    altura: 176,
    nascimento: "2000-02-13",
    ano_chegada: 2024,
    nacionalidade: "Venezuelano",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
    ],
    imagem: imagensDisponiveis["José Martínez"],
    ativo: true,
  },
  {
    nome: "Allan",
    posicao: "Volante",
    altura: 182,
    nascimento: "1997-08-26",
    ano_chegada: 2026,
    nacionalidade: "Brasileiro",
    titulos: [
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Allan"],
    ativo: true,
  },
  {
    nome: "Matheus Pereira",
    posicao: "Volante",
    altura: 180,
    nascimento: "1998-06-06",
    ano_chegada: 2026,
    nacionalidade: "Brasileiro",
    titulos: [
            "Campeonato Brasileiro 2015",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Matheus Pereira"],
    ativo: true,
  },
  {
    nome: "André",
    posicao: "Volante",
    altura: 174,
    nasceu: "2007-03-31",
    ano_chegada: 2025,
    nacionalidade: "Brasileiro",
    titulos: [
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["André"],
    ativo: true,
  },
  {
    nome: "Ryan",
    posicao: "Volante",
    altura: 170,
    nascimento: "2005-02-06",
    ano_chegada: 2024,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
    ],
    imagem: imagensDisponiveis["Ryan"],
    ativo: true,
  },

  // ===== MEIAS 2026 =====
  {
    nome: "André Carrillo",
    posicao: "Meia",
    altura: 180,
    nascimento: "1991-06-14",
    ano_chegada: 2024,
    nacionalidade: "Peruano",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["André Carrillo"],
    ativo: true,
  },
  {
    nome: "Rodrigo Garro",
    posicao: "Meia",
    altura: 174,
    nascimento: "1998-01-29",
    ano_chegada: 2024,
    nacionalidade: "Argentino",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Rodrigo Garro"],
    ativo: true,
  },
  {
    nome: "Dieguinho",
    posicao: "Meia",
    altura: 170,
    nascimento: "2006-02-07",
    ano_chegada: 2024,
    nacionalidade: "Brasileiro",
    titulos: [
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Dieguinho"],
    ativo: true,
  },
  {
    nome: "Zakaria Labyad",
    posicao: "Meia",
    altura: 180,
    nascimento: "1993-04-06",
    ano_chegada: 2026,
    nacionalidade: "Marroquino",
    titulos: [
    ],
    imagem: imagensDisponiveis["Zakaria Labyad"],
    ativo: true,
  },
  {
    nome: "Jesse Lingard",
    posicao: "Meia",
    altura: 175,
    nascimento: "1992-12-14",
    ano_chegada: 2026,
    nacionalidade: "Inglês",
    titulos: [],
    imagem: imagensDisponiveis["Jesse Lingard"],
    ativo: true,
  },

  // ===== ATACANTES 2026 =====
  {
    nome: "Yuri Alberto",
    posicao: "Atacante",
    altura: 183,
    nascimento: "2001-04-18",
    ano_chegada: 2022,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Yuri Alberto"],
    ativo: true,
  },
  {
    nome: "Memphis Depay",
    posicao: "Atacante",
    altura: 176,
    nascimento: "1994-10-13",
    ano_chegada: 2024,
    nacionalidade: "Holandês",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Memphis Depay"],
    ativo: true,
  },
  {
    nome: "Vitinho",
    posicao: "Atacante",
    altura: 180,
    nascimento: "1993-10-10",
    ano_chegada: 2025,
    nacionalidade: "Brasileiro",
    titulos: [
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Vitinho"],
    ativo: true,
  },
  {
    nome: "Kayke",
    posicao: "Atacante",
    altura: 180,
    nascimento: "2004-06-11",
    ano_chegada: 2024,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
      "Copa do Brasil 2025",
      "Supercopa 2026" 
    ],
    imagem: imagensDisponiveis["Kayke"],
    ativo: true,
  },
  {
    nome: "Gui Negão",
    posicao: "Atacante",
    altura: 189,
    nascimento: "2006-08-22",
    ano_chegada: 2024,
    nacionalidade: "Brasileiro",
    titulos: [
      "Copa do Brasil 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Gui Negão"],
    ativo: true,
  },
  {
    nome: "Pedro Raul",
    posicao: "Atacante",
    altura: 192,
    nascimento: "1997-06-24",
    ano_chegada: 2024,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Pedro Raul"],
    ativo: true,
  },
  {
    nome: "Kaio César",
    posicao: "Atacante",
    altura: 176,
    nascimento: "2002-08-26",
    ano_chegada: 2026,
    nacionalidade: "Brasileiro",
    titulos: [
      "Supercopa 2026"
    ],
    imagem: imagensDisponiveis["Kaio César"],
    ativo: true,
  },
  {
    nome: "Angel Romero",
    posicao: "Atacante",
    altura: 176,
    nascimento: "1992-07-04",
    ano_chegada: 2022,
    nacionalidade: "Paraguaio",
    titulos: [
      "Campeonato Paulista 2017",
      "Campeonato Paulista 2018",
      "Campeonato Paulista 2025",
      "Campeonato Brasileiro 2015",
      "Campeonato Brasileiro 2017",
      "Copa do Brasil 2025",
    ],
    imagem: imagensDisponiveis["Ângel Romero"],
    ativo: true,
  },

  // ===== ÍDOLOS HISTÓRICOS =====
  {
    nome: "Cássio",
    posicao: "Goleiro",
    altura: 195,
    nascimento: "1987-06-06",
    ano_chegada: 2012,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2018",
      "Copa do Brasil 2022",
      "Campeonato Brasileiro 2023",
      "Copa Libertadores 2012",
      "Mundial de Clubes 2012",
      "Campeonato Paulista 2019",
      "Campeonato Paulista 2020",
      "Campeonato Paulista 2021",
      "Recopa Sul-Americana 2016",
    ],
    imagem: imagensDisponiveis["Cássio"],
    ativo: true,
  },
  {
    nome: "Paolo Guerrero",
    posicao: "Atacante",
    altura: 184,
    nascimento: "1984-01-01",
    ano_chegada: 2015,
    nacionalidade: "Peruano",
    titulos: [
      "Copa Libertadores 2012",
      "Campeonato Brasileiro 2015",
      "Copa do Brasil 2022",
      "Campeonato Paulista 2018",
      "Recopa Sul-Americana 2016",
    ],
    imagem: imagensDisponiveis["Paolo Guerrero"],
    ativo: true,
  },
  {
    nome: "Ronny",
    posicao: "Atacante",
    altura: 186,
    nascimento: "1984-09-21",
    ano_chegada: 2011,
    nacionalidade: "Brasileiro",
    titulos: ["Copa Libertadores 2012", "Campeonato Brasileiro 2015"],
    imagem: null,
    ativo: false,
  },
  {
    nome: "Sheik",
    posicao: "Meia",
    altura: 175,
    nascimento: "1986-06-12",
    ano_chegada: 2014,
    nacionalidade: "Brasileiro",
    titulos: [
      "Copa Libertadores 2012",
      "Copa do Brasil 2022",
      "Copa do Brasil 2009",
      "Campeonato Paulista 2009",
    ],
    imagem: imagensDisponiveis["Sheik"],
    ativo: false,
  },
  {
    nome: "Marcelinho Carioca",
    posicao: "Meia",
    altura: 177,
    nascimento: "1968-04-06",
    ano_chegada: 1993,
    nacionalidade: "Brasileiro",
    titulos: [
      "Copa Libertadores 2000",
      "Mundial de Clubes 2000",
      "Campeonato Brasileiro 1998",
      "Campeonato Brasileiro 1999",
      "Copa do Brasil 2001",
      "Campeonato Paulista 1995",
      "Campeonato Paulista 1997",
      "Campeonato Paulista 1998",
      "Campeonato Paulista 1999",
      "Campeonato Paulista 2000",
      "Campeonato Paulista 2001",
    ],
    imagem: imagensDisponiveis["Marcelinho Carioca"],
    ativo: false,
  },
  {
    nome: "Jo",
    posicao: "Atacante",
    altura: 185,
    nascimento: "1987-03-20",
    ano_chegada: 2018,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Brasileiro 2017",
      "Campeonato Brasileiro 2005",
      "Campeonato Paulista 2017",
    ],
    imagem: imagensDisponiveis["Jô"],
    ativo: false,
  },
  {
    nome: "Cantillo",
    posicao: "Meia",
    altura: 174,
    nascimento: "1993-06-23",
    ano_chegada: 2020,
    nacionalidade: "Colombiano",
    titulos: ["Copa do Brasil 2022", "Campeonato Brasileiro 2023"],
    imagem: imagensDisponiveis["Cantillo"],
    ativo: true,
  },
  {
    nome: "Du Queiroz",
    posicao: "Volante",
    altura: 180,
    nascimento: "1999-07-17",
    ano_chegada: 2021,
    nacionalidade: "Brasileiro",
    titulos: ["Copa do Brasil 2022", "Campeonato Brasileiro 2023"],
    imagem: imagensDisponiveis["Du Queiroz"],
    ativo: true,
  },
  {
    nome: "Giuliano",
    posicao: "Meia",
    altura: 175,
    nascimento: "1990-07-21",
    ano_chegada: 2015,
    nacionalidade: "Brasileiro",
    titulos: [

    ],
    imagem: imagensDisponiveis["Giuliano"],
    ativo: true,
  },
  {
    nome: "Rivellino",
    posicao: "Meia",
    altura: 173,
    nascimento: "1952-01-01",
    ano_chegada: 1965,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 1966",
      "Campeonato Paulista 1968",
      "Campeonato Paulista 1972",
      "Campeonato Paulista 1973",
      "Campeonato Paulista 1974",
    ],
    imagem: imagensDisponiveis["Rivellino"],
    ativo: false,
  },
  {
    nome: "Sócrates",
    posicao: "Meia",
    altura: 183,
    nascimento: "1954-12-19",
    ano_chegada: 1978,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 1979",
      "Campeonato Paulista 1980",
      "Campeonato Paulista 1982",
      "Campeonato Paulista 1983",
    ],
    imagem: imagensDisponiveis["Sócrates"],
    ativo: false,
  },
  {
    nome: "Neto",
    posicao: "Meia",
    altura: 175,
    nascimento: "1961-02-09",
    ano_chegada: 1989,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Brasileiro 1990",
      "Supercopa do Brasil 1991",
      "Campeonato Paulista 1997",
    ],
    imagem: imagensDisponiveis["Neto"],
    ativo: false,
  },
  {
    nome: "Wladimir",
    posicao: "Lateral",
    altura: 174,
    nascimento: "1956-12-27",
    ano_chegada: 1974,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 1977",
      "Campeonato Paulista 1979",
      "Campeonato Paulista 1981",
      "Campeonato Paulista 2001",
    ],
    imagem: imagensDisponiveis["Wladimir"],
    ativo: false,
  },
  {
    nome: "Basílio",
    posicao: "Atacante",
    altura: 175,
    nascimento: "1955-12-16",
    ano_chegada: 1973,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 1977",
      "Campeonato Paulista 1979",
      "Campeonato Paulista 1982",
      "Campeonato Paulista 1983",
    ],
    imagem: imagensDisponiveis["Basílio"],
    ativo: false,
  },
  {
    nome: "Luizinho",
    posicao: "Atacante",
    altura: 167,
    nascimento: "1931-11-28",
    ano_chegada: 1951,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 1951",
      "Campeonato Paulista 1952",
      "Campeonato Paulista 1954",
    ],
    imagem: imagensDisponiveis["Luizinho"],
    ativo: false,
  },
  {
    nome: "Gylmar",
    posicao: "Goleiro",
    altura: 178,
    nascimento: "1931-09-11",
    ano_chegada: 1951,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 1954",
      "Campeonato Paulista 1956",
      "Campeonato Paulista 1957",
      "Campeonato Paulista 1958",
      "Campeonato Paulista 1959",
      "Campeonato Paulista 1960",
      "Campeonato Paulista 1961",
      "Torneio Rio-São Paulo 1954",
      "Torneio Rio-São Paulo 1955",
      "Torneio Rio-São Paulo 1958",
    ],
    imagem: imagensDisponiveis["Gylmar"],
    ativo: false,
  },
  {
    nome: "Cláudio",
    posicao: "Atacante",
    altura: 171,
    nascimento: "1934-04-15",
    ano_chegada: 1955,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 1956",
      "Campeonato Paulista 1957",
      "Campeonato Paulista 1958",
      "Campeonato Paulista 1959",
      "Campeonato Paulista 1960",
      "Torneio Rio-São Paulo 1955",
      "Torneio Rio-São Paulo 1958",
    ],
    imagem: imagensDisponiveis["Cláudio"],
    ativo: false,
  },
  {
    nome: "Vampeta",
    posicao: "Volante",
    altura: 181,
    nascimento: "1968-01-04",
    ano_chegada: 1996,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Brasileiro 1998",
      "Campeonato Brasileiro 1999",
      "Copa do Brasil 2002",
      "Campeonato Paulista 1999",
      "Campeonato Paulista 2000",
      "Copa do Mundo de Clubes 2000",
    ],
    imagem: imagensDisponiveis["Vampeta"],
    ativo: false,
  },
  {
    nome: "Dida",
    posicao: "Goleiro",
    altura: 196,
    nascimento: "1973-09-07",
    ano_chegada: 1999,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Brasileiro 2000",
      "Copa do Brasil 2002",
      "Copa Sul-Americana 1998",
      "Campeonato Paulista 2001",
      "Copa do Brasil 2001",
      "Copa Sul-Americana 2004",
    ],
    imagem: imagensDisponiveis["Dida"],
    ativo: false,
  },
  {
    nome: "Casagrande",
    posicao: "Atacante",
    altura: 181,
    nascimento: "1962-12-04",
    ano_chegada: 1981,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 1982",
      "Campeonato Paulista 1983",
      "Campeonato Brasileiro 1983",
    ],
    imagem: imagensDisponiveis["Casagrande"],
    ativo: false,
  },
  {
    nome: "Ronaldo Fenômeno",
    posicao: "Atacante",
    altura: 183,
    nascimento: "1976-09-18",
    ano_chegada: 2009,
    nacionalidade: "Brasileiro",
    titulos: ["Copa do Brasil 2009", "Campeonato Paulista 2009"],
    imagem: imagensDisponiveis["Ronaldo Fenômeno"],
    ativo: false,
  },
  {
    nome: "Ricardinho",
    posicao: "Meia",
    altura: 168,
    nascimento: "1976-03-20",
    ano_chegada: 1998,
    nacionalidade: "Brasileiro",
    titulos: [
      "Copa Libertadores 2000",
      "Mundial de Clubes 2000",
      "Campeonato Brasileiro 1999",
      "Copa do Brasil 2001",
      "Campeonato Paulista 1999",
      "Campeonato Paulista 2000",
      "Copa Sul-Americana 2004",
    ],
    imagem: imagensDisponiveis["Ricardinho"],
    ativo: false,
  },
  {
    nome: "Danilo",
    posicao: "Volante",
    altura: 177,
    nascimento: "1981-11-15",
    ano_chegada: 2010,
    nacionalidade: "Brasileiro",
    titulos: [
      "Copa Libertadores 2012",
      "Mundial de Clubes 2012",
      "Campeonato Brasileiro 2011",
      "Campeonato Brasileiro 2015",
      "Copa do Brasil 2016",
      "Copa do Brasil 2022",
      "Campeonato Paulista 2013",
      "Copa do Brasil 2019",
    ],
    imagem: imagensDisponiveis["Danilo"],
    ativo: false,
  },
  {
    nome: "Carlos Tevez",
    posicao: "Atacante",
    altura: 171,
    nascimento: "1984-10-15",
    ano_chegada: 2015,
    nacionalidade: "Argentino",
    titulos: [
      "Copa do Brasil 2016",
      "Campeonato Brasileiro 2015",
      "Copa Sul-Americana 2016",
    ],
    imagem: imagensDisponiveis["Carlos Tevez"],
    ativo: false,
  },
  {
    nome: "Talles Magno",
    posicao: "Atacante",
    altura: 186,
    nascimento: "1989-09-14",
    ano_chegada: 2024,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2025",
    ],
    imagem: imagensDisponiveis["Talles Magno"],
    ativo: true,
  },
  {
    nome: "Fagner",
    posicao: "Lateral",
    altura: 178,
    nascimento: "1989-09-14",
    ano_chegada: 2018,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2018",
      "Copa do Brasil 2022",
      "Campeonato Brasileiro 2023",
    ],
    imagem: imagensDisponiveis["Fagner"],
    ativo: true,
  },
  {
    nome: "Roger Guedes",
    posicao: "Atacante",
    altura: 182,
    nascimento: "1996-09-02",
    ano_chegada: 2021,
    nacionalidade: "Brasileiro",
    titulos: [],
    imagem: imagensDisponiveis["Roger Guedes"],
    ativo: true,
  },
  {
    nome: "Renato Augusto",
    posicao: "Meia",
    altura: 186,
    nascimento: "1988-02-08",
    ano_chegada: 2013,
    nacionalidade: "Brasileiro",
    titulos: [
      "Recopa Sudamericana",
      "Campeonato Paulista 2013",
      "Campeonato Brasileiro 2015",
    ],
    imagem: imagensDisponiveis["Renato Augusto"],
    ativo: false,
  },
  {
    nome: "Matias Rojas",
    posicao: "Meia",
    altura: 186,
    nascimento: "1995-11-03",
    ano_chegada: 2023,
    nacionalidade: "Paraguaio",
    titulos: [],
    imagem: imagensDisponiveis["Matias Rojas"],
    ativo: true,
  },
  {
    nome: "Wesley Gassova",
    posicao: "Lateral",
    altura: 180,
    nascimento: "2005-03-05",
    ano_chegada: 2022,
    nacionalidade: "Brasileiro",
    titulos: [],
    imagem: imagensDisponiveis["Wesley"],
    ativo: true,
  },
  {
    nome: "Murillo",
    posicao: "Zagueiro",
    altura: 180,
    nascimento: "2002-07-04",
    ano_chegada: 2023,
    nacionalidade: "Brasileiro",
    titulos: [],
    imagem: imagensDisponiveis["Murillo"],
    ativo: true,
  },
  {
    nome: "Marquinhos",
    posicao: "Zagueiro",
    altura: 183,
    nascimento: "1994-05-14",
    ano_chegada: 2012,
    nacionalidade: "Brasileiro",
    titulos: [
      "Copa Libertadores 2012",
    ],
    imagem: imagensDisponiveis["Marquinhos"],
    ativo: true,
  },
  {
    nome: "Malcom",
    posicao: "Atacante",
    altura: 172,
    nascimento: "1997-02-26",
    ano_chegada: 2014,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2015"
    ],
    imagem: imagensDisponiveis["Malcom"],
    ativo: true,
  },
  {
    nome: "Willian",
    posicao: "Atacante",
    altura: 175,
    nascimento: "1988-08-09",
    ano_chegada: 2005,
    nacionalidade: "Brasileiro",
    titulos: [
    ],
    imagem: imagensDisponiveis["Willian"],
    ativo: true,
  },
  {
    nome: "Fabio Santos",
    posicao: "Lateral",
    altura: 179,
    nascimento: "1985-09-16",
    ano_chegada: 2011,
    nacionalidade: "Brasileiro",
    titulos: [
      "Copa Libertadores 2012",
      "Copa do Mundo de Clubes 2012",
      "Campeonato Brasileiro 2011",
      "Campeonato Brasileiro 2015",
      "Recopa Sudamericana 2013",
      "Campeonato Paulista 2013",
    ],
    imagem: imagensDisponiveis["Fabio Santos"],
    ativo: false,
  },
  {
    nome: "Gil da Goiaba",
    posicao: "Zagueiro",
    altura: 191,
    nascimento: "1987-06-12",
    ano_chegada: 2013,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2013",
      "Recopa Sudamericana 2013",
      "Campeonato Brasileiro 2015",
    ],
    imagem: imagensDisponiveis["Gil"],
    ativo: false,
  },
  {
    nome: "Luan",
    posicao: "Atacante",
    altura: 180,
    nascimento: "1993-03-27",
    ano_chegada: 2019,
    nacionalidade: "Brasileiro",
    titulos: [
    ],
    imagem: imagensDisponiveis["Luan"],
    ativo: false,
  },
  {
    nome: "Vagner Love",
    posicao: "Atacante",
    altura: 171,
    nascimento: "1984-06-11",
    ano_chegada: 2015,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2019",
    ],
    imagem: imagensDisponiveis["Vagner Love"],
    ativo: false,
  },
  {
    nome: "Douglas",
    posicao: "Meia",
    altura: 176,
    nascimento: "1982-02-18",
    ano_chegada: 2008,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2013",
      "Campeonato Paulista 2009",
      "Copa do Brasil 2009",
      "Copa Libertadores 2012",
      "Mundial de Clubes 2012",
      "Recopa Sudamericana 2013",
      "Série B 2008",
    ],
    imagem: imagensDisponiveis["Douglas"],
    ativo: false,
  },
  {
    nome: "Adson",
    posicao: "Atacante",
    altura: 171,
    nascimento: "2000-10-06",
    ano_chegada: 2021,
    nacionalidade: "Brasileiro",
    titulos: [
    ],
    imagem: imagensDisponiveis["Adson"],
    ativo: true,
  },
  {
    nome: "Rincon",
    posicao: "Meia",
    altura: 185,
    nascimento: "1966-08-14",
    ano_chegada: 1998,
    nacionalidade: "Colombiano",
    titulos: [
      "Campeonato Paulista ?",
      "Copa Mundial de Clubes 2000",
      "Campeonato Brasileiro 98",
      "Campeonato Brasileiro 99",
    ],
     imagem: imagensDisponiveis["Rincon"],
     ativo: false,
   },
  {
    nome: "Edilson Capetinha/Capeta",
    posicao: "Atacante",
    altura: 168,
    nascimento: "1971-09-17",
    ano_chegada: 1997,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 99",
      "Copa Mundial de Clubes 2000",
      "Campeonato Brasileiro 98",
      "Campeonato Brasileiro 99",
    ],
    imagem: imagensDisponiveis["Edilson"],
    ativo: false,
  },
  {
    nome: "Romarinho",
    posicao: "Atacante",
    altura: 176,
    nascimento: "1990-12-12",
    ano_chegada: 2012,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2013",
      "Copa Libertadores 2012",
      "Copa do Mundo de Clubes 2012",
      "Recopa Sudamericana 2013",
    ],
    imagem: imagensDisponiveis["Romarinho"],
    ativo: true,
  },
  {
    nome: "Jadson",
    posicao: "Meia",
    altura: 169,
    nascimento: "1983-10-05",
    ano_chegada: 2014,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2019",
      "Campeonato Paulista 2018",
      "Campeonato Paulista 2017",
      "Campeonato Brasileiro 2017",
      "Campeonato Brasileiro 2015",
    ],
    imagem: imagensDisponiveis["Jadson"],
    ativo: false,
  },
  {
    nome: "Rodriguinho",
    posicao: "Meia",
    altura: 177,
    nascimento: "1988-03-27",
    ano_chegada: 2013,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2017",
      "Campeonato Paulista 2018",
      "Campeonato Brasileiro 2017",
      "Campeonato Brasileiro 2018",
    ],
    imagem: imagensDisponiveis["Rodriguinho"],
    ativo: false,
  },
  {
    nome: "Dentinho",
    posicao: "Atacante",
    altura: 176,
    nascimento: "1989-01-19",
    ano_chegada: 2007,
    nacionalidade: "Brasileiro",
    titulos: [
      "Campeonato Paulista 2009",
      "Série B 2008",
      "Copa do Brasil 2009",
    ],
    imagem: imagensDisponiveis["Dentinho"],
    ativo: true,
  },
  //Quebrados

  {
    nome: "A. Pistache",
    posicao: "Meia",
    altura: 160,
    nascimento: "2007-02-20",
    ano_chegada: 2021,
    nacionalidade: "Brasileiro",
    titulos: [
      "THE LAST DANCE"
    ],
    imagem: imagensDisponiveis["A Pistache"],
    ativo: true,
  },
];

export const posicoesValidas = [
  "Goleiro",
  "Zagueiro",
  "Lateral",
  "Volante",
  "Meia",
  "Atacante",
];

export const nacionalidadesValidas = [
  "Brasileiro",
  "Argentino",
  "Peruano",
  "Paraguaio",
  "Equatoriano",
  "Venezuelano",
  "Holandês",
  "Colombiano",
  "Marroquino",
  "Inglês",
  "Uruguaio",
];

export const getFaixaAltura = (altura) => {
  if (altura < 180) return "Abaixo de 1.80";
  if (altura <= 185) return "1.80 - 1.85";
  if (altura <= 190) return "1.86 - 1.90";
  return "Acima de 1.90";
};

export const getIdade = (nascimento) => {
  if (!nascimento) return 0;
  const hoje = new Date();
  const nasc = new Date(nascimento);
  let idade = hoje.getFullYear() - nasc.getFullYear();
  const mes = hoje.getMonth() - nasc.getMonth();
  if (mes < 0 || (mes === 0 && hoje.getDate() < nasc.getDate())) {
    idade--;
  }
  return Math.max(0, idade);
};

export const getIdadeCorrigida = (jogador) => {
  return getIdade(jogador.nascimento) || getIdade(jogador.nacimiento);
};

export const getFaixaIdade = (nascimento) => {
  const idade = getIdade(nascimento);
  if (idade < 23) return "Menos de 23";
  if (idade <= 27) return "23 - 27";
  if (idade <= 32) return "28 - 32";
  return "Mais de 32";
};

export const getImagemUrl = (jogador, tipo = "normal") => {
  if (jogador.imagem && tipo !== "misterio") {
    return `/img/jogadores/${jogador.imagem}`;
  }
  if (tipo === "misterio") {
    return `/img/jogadores/misterio.svg`;
  }
  return `/img/jogadores/placeholder.svg`;
};

export const contadorJogadores = () => {
  return jogadores.length;
};
